version: "3.8"
services:
  app:
    image: no-code-architects-toolkit:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - storage:/app/storage
    restart: unless-stopped

volumes:
  storage:
    driver: local